# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

AdminUser.create([
  { :email => "admin@example.com", :encrypted_password => "$2a$10$kchGDcWaHFLHgY1LM8nMNeTmNSjzk3.tGghYzfMsoTDRiRdlgGUFi", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => "2013-09-08 06:46:19", :updated_at => "2013-09-08 06:46:19" }
], :without_protection => true )



Election.create([
  { :name => "제5회 전국동시지방선거", :held_on => "2010-06-02", :term_started_on => "2010-07-01", :term_ended_on => "2014-06-30", :note => "통합창원시출범", :created_at => "2013-09-08 06:14:40", :updated_at => "2013-09-08 06:14:40" }
], :without_protection => true )



Position.create([
  { :name => "서울특별시장", :type_name => "광역자치단체장", :type_code => 3, :district => "서울특별시", :created_at => "2013-09-08 06:16:22", :updated_at => "2013-09-08 06:16:22" },
  { :name => "부산광역시장", :type_name => "광역자치단체장", :type_code => 3, :district => "부산광역시", :created_at => "2013-09-08 06:16:22", :updated_at => "2013-09-08 06:16:22" },
  { :name => "대구광역시장", :type_name => "광역자치단체장", :type_code => 3, :district => "대구광역시", :created_at => "2013-09-08 06:18:15", :updated_at => "2013-09-08 06:18:15" },
  { :name => "인천광역시장", :type_name => "광역자치단체장", :type_code => 3, :district => "인천광역시", :created_at => "2013-09-08 06:18:15", :updated_at => "2013-09-08 06:18:15" },
  { :name => "광주광역시장", :type_name => "광역자치단체장", :type_code => 3, :district => "광주광역시", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" },
  { :name => "대전광역시장", :type_name => "광역자치단체장", :type_code => 3, :district => "대전광역시", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" },
  { :name => "울산광역시장", :type_name => "광역자치단체장", :type_code => 3, :district => "울산광역시", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" },
  { :name => "경기도지사", :type_name => "광역자치단체장", :type_code => 3, :district => "경기도", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" },
  { :name => "강원도지사", :type_name => "광역자치단체장", :type_code => 3, :district => "강원도", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" },
  { :name => "충청북도지사", :type_name => "광역자치단체장", :type_code => 3, :district => "충청북도", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" },
  { :name => "충청남도지사", :type_name => "광역자치단체장", :type_code => 3, :district => "충청남도", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" },
  { :name => "전라북도지사", :type_name => "광역자치단체장", :type_code => 3, :district => "전라북도", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" },
  { :name => "전라남도지사", :type_name => "광역자치단체장", :type_code => 3, :district => "전라남도", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" },
  { :name => "경상북도지사", :type_name => "광역자치단체장", :type_code => 3, :district => "경상북도", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" },
  { :name => "경상남도지사", :type_name => "광역자치단체장", :type_code => 3, :district => "경상남도", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" },
  { :name => "제주특별자치도지사", :type_name => "광역자치단체장", :type_code => 3, :district => "제주특별자치도", :created_at => "2013-09-08 06:17:56", :updated_at => "2013-09-08 06:17:56" }
], :without_protection => true )


